/* Crear base de datos dbGamarraMarket */
DROP DATABASE IF EXISTS dbGamarraMarket;
CREATE DATABASE dbGamarraMarket
DEFAULT CHARACTER SET utf8;

/* Poner en uso la base de datos dbGamarraMarket */
USE dbGamarraMarket;

/* Eliminar base de datos dbGamarraMarket opcional */
DROP DATABASE dbGamarraMarket;
 
 /*crear tabla cliente*/
 CREATE TABLE CLIENTE
 (
 ID INT ,
 TIPO_DOCUMENTO CHAR(3),
 NUMERO_DOCUMENTO CHAR(9),
 NOMBRES VARCHAR (60),
 APELLIDOS VARCHAR (90),
 EMAIL VARCHAR (80),
 CELULAR CHAR(9),
 FECHA_NACIMINETO DATE,
 ACTIVO BOOL,
 CONSTRAINT CLIENTE_PK PRIMARY KEY (ID)
 );
 ALTER TABLE CLIENTE CHANGE APELLIDOS APELLIDOS INT AUTO_INCREMENT;
  
/* Listar estructura de tabla CLIENTE */
SHOW COLUMNS IN CLIENTE;

/* Listar tablas existentes en la base de datos en uso */
SHOW TABLES;

/* Agregar columna estado civil */
ALTER TABLE CLIENTE
	ADD COLUMN ESTADO_CIVIL CHAR(1);

/* Eliminar columna fecha_nacimiento */
ALTER TABLE CLIENTE
	DROP COLUMN FECHA_NACIMINETO;

/* Eliminar la tabla CLIENTE */
DROP TABLE CLIENTE;

 /*crear tabla ventA*/
 CREATE TABLE VENTA
 (
 ID INT ,
FECHA_HORA TIME,
 ACTIVO BOOL,
 CLIENTE_ID INT,
 VENDEDOR_ID INT,
 CONSTRAINT VENTA_PK PRIMARY KEY (ID)
 );
 
/* Crear relación VENTA_CLIENTE */
ALTER TABLE VENTA
	ADD CONSTRAINT VENTA_CLIENTE FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE (ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;

 /*listar estructura de VENTA*/
 SHOW COLUMNS IN VENTA;

/* Eliminar la relación VENTA_CLIENTE */
ALTER TABLE VENTA
	DROP CONSTRAINT VENTA_CLIENTE;

/*crear tabla VENDEDOR*/
 CREATE TABLE VENDEDOR
 (
 ID INT ,
TIPO_DOCUMENTO CHAR(3),
NUMERO_DOCUMENTO CHAR(15),
NOMBRES VARCHAR(60),
APELLIDOS VARCHAR(90),
SALARIO DECIMAL(8.2),
CELULAR CHAR(9),
EMAIL VARCHAR(80),
 ACTIVO BOOL,
 CONSTRAINT VENDEDOR_PK PRIMARY KEY (ID)
 );
 
 /*listar estructura de VENDEDOR*/
 SHOW COLUMNS IN VENDEDOR;
 
/* Crear relación VENTA_VENDEDOR */
ALTER TABLE VENTA
	ADD CONSTRAINT VENTA_VENDEDOR FOREIGN KEY (VENDEDOR_ID)
    REFERENCES VENDEDOR (ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;

/*crear tabla VENTA_DETALLE*/
 CREATE TABLE VENTA_DETALLE
 (
 ID INT ,
CANTIDAD INT,
VENTA_ID INT,
PRENDA_ID INT,
 CONSTRAINT VENTA_DETALLE_PK PRIMARY KEY (ID)
 );
 
 /* Crear relación VENTA_DETALLE_VENTA */
ALTER TABLE VENTA_DETALLE
	ADD CONSTRAINT VENTA_DETALLE_VENTA FOREIGN KEY (VENTA_ID)
    REFERENCES VENTA (ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;

/*crear tabla PRENDA*/
 CREATE TABLE PRENDA
 (
ID INT,
DESCRIPCION VARCHAR(90),
MARCA VARCHAR(60),
CANTIDAD INT,
TALLA VARCHAR(10),
PRECIO DECIMAL(8.2),
ACTIVO BOOL,
 CONSTRAINT PRENDA_PK PRIMARY KEY (ID)
 );
 
 /* Crear relación VENTA_DETALLE_VENTA */
ALTER TABLE VENTA_DETALLE
	ADD CONSTRAINT VENTA_DETALLE_PRENDA FOREIGN KEY (PRENDA_ID)
    REFERENCES PRENDA (ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
;
/* Listar relaciones de tablas de la base de datos activa */
SELECT 
    i.constraint_name, k.table_name, k.column_name, 
    k.referenced_table_name, k.referenced_column_name
FROM 
    information_schema.TABLE_CONSTRAINTS i 
LEFT JOIN information_schema.KEY_COLUMN_USAGE k 
ON i.CONSTRAINT_NAME = k.CONSTRAINT_NAME 
WHERE i.CONSTRAINT_TYPE = 'FOREIGN KEY' 
AND i.TABLE_SCHEMA = DATABASE();

